easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - ressource: '@EasyAdminBundle/Controller/RegistrationController.php'
#        - App\Entity\Product
#        - App\Entity\Category
        - App\Entity\User
